### PR TITLE
JSDoc Improvements

### PR DESCRIPTION
**Pull request by DjDeveloperr**
## What kind of change does this PR introduce?

Docs update

## What is the current behavior?

Current JSDoc doesn't include complete types and other things. (https://github.com/supabase/postgrest-js/issues/111)

## What is the new behavior?

JSDoc is pretty much improved overall.

## Additional context

Its my first PR to an open source project, let me know if there's anything wrong!

### CODE REVIEW

**Comment by kiwicopple** [comment]
Hi @DjDeveloperr awesome job for you first PR! Cool that you got into JSDoc too - you looked at some of the features to make sure everything was covered. A couple of things:

1. We don't need the ` - ` added to all of the descriptions: this actaully breaks our documentation a bit
2. We can removed the `{types}` from the doc comments. SInce this is TypeScript, it's better to rely on the Type definitions in the code.

That will only leave your `@link` comments at the top, but i'll be happy to merge them if you want!

**Comment by DjDeveloperr** [comment]
Thank you! It would be cool if you are able to merge. However, is there anything more I can do about it? Looking forward to contribute c:

**Comment by kiwicopple** [comment]
Hey @DjDeveloperr - you will need to revert all your changes from line 20 and below :) 

We only need the changes you made at the top

**Comment by kiwicopple** [comment]
That's great! Thanks @DjDeveloperr 👍

**Pull request merged**
